Trying out https://www.youtube.com/watch?v=GB9ByFAIAH4&t=103s
First import numpy as np

In [8]:
import numpy as np

Initialize a 1-D array

In [9]:
a = np.array([1,2,3])

In [10]:
a

array([1, 2, 3])

In [11]:
print(a)
print(a.ndim) # Check array's dimensions

[1 2 3]
1


In [12]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # Initialize a 2-d array
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [13]:
print(b)
print(b.ndim)

[[9. 8. 7.]
 [6. 5. 4.]]
2


In [17]:
trying_3_d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
c = trying_3_d_array

In [19]:
print(c)
print(c.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [15]:
trying_3_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(trying_3_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Still don't know how to create 3D array